### ISSUE TITLE
Add Temporary Website on Production URL

### ISSUE THREAD

**Issue by timrolsh** [timrolsh/Songscope#7]
The production URL ([songscope.org](https://songscope.org)) is currently registered, but there is nothing on it. 
- [ ] Add a basic HTML site, make it one file that says that the app is currently in development. Provide a link to the GitHub page where people can contribute if they would like
- [ ] Set up either a hosting system on a cloud provider or host it locally

**Comment by yusufsallam64** [comment]
Do we still need this issue open?
